# -*- coding: utf-8 -*-
"""Impact Of Time on Air Quality

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1396rCouumOTmLCqbfrQehUu8eTpRoDYD
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


data = pd.read_csv('/content/air-quality-india.csv')

data['Timestamp'] = pd.to_datetime(data['Timestamp'])


data['day_of_week'] = data['Timestamp'].dt.dayofweek  # Monday=0, Sunday=6
data['day_name'] = data['Timestamp'].dt.day_name()  # Full name of the day
data['hour'] = data['Timestamp'].dt.hour  # Extract the hour from the timestamp


pm25_stats = data['PM2.5'].describe()
print("PM2.5 Statistics:")
print(pm25_stats)

plt.figure(figsize=(12, 6))
plt.plot(data['Timestamp'], data['PM2.5'], alpha=0.5, label='PM2.5 levels')
plt.xlabel('Time')
plt.ylabel('PM2.5 Level')
plt.title('PM2.5 Levels Over Time')
plt.legend()
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x='hour', y='PM2.5', data=data, palette='viridis')
plt.xlabel('Hour of the Day')
plt.ylabel('PM2.5 Level')
plt.title('PM2.5 Levels by Hour of the Day')
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x='day_name', y='PM2.5', data=data, palette='viridis')
plt.xlabel('Day of the Week')
plt.ylabel('PM2.5 Level')
plt.title('PM2.5 Levels by Day of the Week')
plt.show()

peak_hours = data.groupby('hour')['PM2.5'].mean().sort_values(ascending=False)
print("Peak Hours for PM2.5 Levels:")
print(peak_hours)